### ISSUE TITLE
[Bug] Call Audio/Mic not working

### ISSUE THREAD

**Issue by icodelifee** [team-telnyx/telnyx-webrtc-flutter#13]
**Bug Category**
- [ ] Credential Login
- [ ] Token Login
- [x] Local Audio Issue
- [x] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [ ] Other

**SDK Version**
telnyx_webrtc: ^0.0.3

**Describe the bug**
After the receiver accepts the call, both the caller nor the receiver cannot hear any audio from the device 

**Expected behavior**
The caller and receiver should be able to hear and speak

** Device (please complete the following information):**
- OS Version: Android 12

**Logs**
` INVITATION ANSWERED :: {jsonrpc: 2.0, id: 67246, method: telnyx_rtc.answer, params: {callID: Instance of 'Uuid', variables: {Event-Name: CHANNEL_DATA, Core-UUID: efaeab2c-2067-42d3-b973-37aa4330ac97, FreeSWITCH-Hostname: b2bua-rtc.tel-sy1-ibm-prod-133, FreeSWITCH-Switchname: b2bua-rtc.tel-sy1-ibm-prod-133, FreeSWITCH-IPv4: 10.33.0.80, FreeSWITCH-IPv6: ::1, Event-Date-Local: 2022-08-19 14:24:34, Event-Date-GMT: Fri, 19 Aug 2022 14:24:34 GMT, Event-Date-Timestamp: 1660919074493112, Event-Calling-File: switch_channel.c, Event-Calling-Function: switch_channel_get_variables_prefix, Event-Calling-Line-Number: 4576, Event-Sequence: 163053}}}`

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee. Can You please test call via our test tool here:

https://webrtc.telnyx.com/

You can log in with sip credentials and call your flutter app. It would be nice to confirm if in this case there is still no audio on both ends so we can isolate it to the flutter SDK.

**Comment by Oliver-Zimmerman** [comment]
@icodelifee I just tested one more time with the example app and it all seems to be working correctly. 

Can you have a look at the reference application here:
https://github.com/team-telnyx/telnyx-webrtc-flutter/tree/main/lib

It's a very simple implementation but should give you a good idea of how it works. 

Do you have the correct permissions in the manifest?

**Comment by icodelifee** [comment]
> Hi @icodelifee. Can You please test call via our test tool here:
> 
> [webrtc.telnyx.com](https://webrtc.telnyx.com/)
> 
> You can log in with sip credentials and call your flutter app. It would be nice to confirm if in this case there is still no audio on both ends so we can isolate it to the flutter SDK.

I tried the webrtc app and was able to make calls using credentials but for my use case, we only require outbound calls

**Comment by icodelifee** [comment]
![Screenshot 2022-08-19 at 9 29 55 PM](https://user-images.githubusercontent.com/18023153/185659690-b60d7b02-6f4d-4bdb-bcac-7758605bffc6.png)
Yep i think i do have correct permissions


> @icodelifee I just tested one more time with the example app and it all seems to be working correctly.
> 
> Can you have a look at the reference application here: [`main`/lib](https://github.com/team-telnyx/telnyx-webrtc-flutter/tree/main/lib?rgh-link-date=2022-08-19T15%3A47%3A15Z)
> 
> It's a very simple implementation but should give you a good idea of how it works.
> 
> Do you have the correct permissions in the manifest?

**Comment by icodelifee** [comment]
I tried using the example app
![image](https://user-images.githubusercontent.com/18023153/185660230-30816c56-e8db-420b-9be1-f4c3907fec59.png)

**Comment by icodelifee** [comment]
Also facing this issue, even though i tried using the same organization number in webrtc.telnyx.com where it worked fine
![Screenshot 2022-08-19 at 9 35 25 PM](https://user-images.githubusercontent.com/18023153/185660554-3aeb17e8-effb-44b3-a660-171e9faa8a6a.png)

**Comment by Oliver-Zimmerman** [comment]
> > Hi @icodelifee. Can You please test call via our test tool here:
> > [webrtc.telnyx.com](https://webrtc.telnyx.com/)
> > You can log in with sip credentials and call your flutter app. It would be nice to confirm if in this case there is still no audio on both ends so we can isolate it to the flutter SDK.
> 
> I tried the webrtc app and was able to make calls using credentials but for my use case, we only require outbound calls

So in this case please log into that web app and then call the web app credentials from your flutter application

**Comment by Oliver-Zimmerman** [comment]
> Also facing this issue, even though i tried using the same organization number in webrtc.telnyx.com where it worked fine ![Screenshot 2022-08-19 at 9 35 25 PM](https://user-images.githubusercontent.com/18023153/185660554-3aeb17e8-effb-44b3-a660-171e9faa8a6a.png)

Please share the exact invite message sent on the socket

**Comment by Oliver-Zimmerman** [comment]
> I tried using the example app ![image](https://user-images.githubusercontent.com/18023153/185660230-30816c56-e8db-420b-9be1-f4c3907fec59.png)

Are you on the Main branch? This error isn't happening for me currently. I will spend some time this weekend looking into this though.

There is a refactor that we have planned which will simplify this flow and might indirectly fix this issue

**Comment by icodelifee** [comment]
> > Also facing this issue, even though i tried using the same organization number in webrtc.telnyx.com where it worked fine ![Screenshot 2022-08-19 at 9 35 25 PM](https://user-images.githubusercontent.com/18023153/185660554-3aeb17e8-effb-44b3-a660-171e9faa8a6a.png)
> 
> Please share the exact invite message sent on the socket

`I/flutter ( 2366): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 2366): │ #0   _HomeScreenState._callDestination (package:telnyx_flutter_webrtc/view/screen/home_screen.dart:37:12)
package:telnyx_flutter_webrtc/…/screen/home_screen.dart:37
I/flutter ( 2366): │ #1   _HomeScreenState.build.<anonymous closure> (package:telnyx_flutter_webrtc/view/screen/home_screen.dart:74:21)
package:telnyx_flutter_webrtc/…/screen/home_screen.dart:74
I/flutter ( 2366): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2366): │ 💡 Calling!
I/flutter ( 2366): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/FlutterWebRTCPlugin( 2366): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
D/FlutterWebRTCPlugin( 2366): MediaStream id: 5e7c3178-5b69-499b-96ae-8f59ce1a6fd6
I/org.webrtc.Logging( 2366): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging( 2366): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging( 2366): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging( 2366): WebRtcAudioEffectsExternal: setNS(true)
D/FlutterWebRTCPlugin( 2366): onIceGatheringChangeGATHERING
D/FlutterWebRTCPlugin( 2366): onIceCandidate
I/chatty  ( 2366): uid=10569(com.telnyx.telnyx_flutter_webrtc) signaling_threa identical 1 line
3
D/FlutterWebRTCPlugin( 2366): onIceCandidate
I/flutter ( 2366): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 2366): │ #0   TxSocket.send (package:telnyx_webrtc/tx_socket.dart:36:13)
package:telnyx_webrtc/tx_socket.dart:36
I/flutter ( 2366): │ #1   Peer._send (package:telnyx_webrtc/peer/peer.dart:366:13)
package:telnyx_webrtc/peer/peer.dart:366
I/flutter ( 2366): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2366): │ 💡 TxSocket :: send : 
I/flutter ( 2366): │ 💡 
I/flutter ( 2366): │ 💡 {"id":"Instance of 'Uuid'","jsonrpc":"2.0","method":"telnyx_rtc.invite","params":{"dialogParams":{"attach":false,"audio":true,"callID":"Instance of 'Uuid'","caller_id_name":"callerName","caller_id_number":"Fake Number","clientState":"RmFrZSBTdGF0ZQ==","destination_number":"+919074812071","remote_caller_id_name":"","screenShare":false,"useStereo":false,"userVariables":[],"video":false},"sdp":"v=0\r\no=- 473545682443468629 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS 5e7c3178-5b69-499b-96ae-8f59ce1a6fd6\r\nm=audio 37197 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 192.168.18.236\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate:2093286574 1 udp 2122260223 192.168.18.236 37197 typ host generation 0 network-id 3 network-cost 10\r\na=candidate:559267639 1 udp 2122202367 ::1 42072 typ host generation 0 network-id 2\r\na=candidate:1510613869 1 udp 2122129151 127.0.0.1 38856 typ host generation 0 network-id 1\r\
I/flutter ( 2366): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/FlutterWebRTCPlugin( 2366): onIceCandidate
I/flutter ( 2366): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 2366): │ #0   TelnyxClient._onMessage (package:telnyx_webrtc/telnyx_client.dart:234:13)
package:telnyx_webrtc/telnyx_client.dart:234
I/flutter ( 2366): │ #1   TelnyxClient.connect.<anonymous closure> (package:telnyx_webrtc/telnyx_client.dart:89:9)
package:telnyx_webrtc/telnyx_client.dart:89
I/flutter ( 2366): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2366): │ 💡 DEBUG MESSAGE: {"jsonrpc":"2.0","id":"Instance of 'Uuid'","result":{"message":"CALL CREATED","callID":"Instance of 'Uuid'","sessid":"fe4849db-c9bb-41c3-802d-07fbbf212368"}}
I/flutter ( 2366): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 2366): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 2366): │ #0   TelnyxClient._onMessage (package:telnyx_webrtc/telnyx_client.dart:237:17)
package:telnyx_webrtc/telnyx_client.dart:237
I/flutter ( 2366): │ #1   TelnyxClient.connect.<anonymous closure> (package:telnyx_webrtc/telnyx_client.dart:89:9)
package:telnyx_webrtc/telnyx_client.dart:89
I/flutter ( 2366): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 2366): │ 💡 Received WebSocket message :: {"jsonrpc":"2.0","id":"Instance of 'Uuid'","result":{"message":"CALL CREATED","callID":"Instance of 'Uuid'","sessid":"fe4849db-c9bb-41c3-802d-07fbbf212368"}}
I/flutter ( 2366): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
`

**Comment by icodelifee** [comment]
> > I tried using the example app ![image](https://user-images.githubusercontent.com/18023153/185660230-30816c56-e8db-420b-9be1-f4c3907fec59.png)
> 
> Are you on the Main branch? This error isn't happening for me currently. I will spend some time this weekend looking into this though.
> 
> There is a refactor that we have planned which will simplify this flow and might indirectly fix this issue

Yes im using the main branch

**Comment by Oliver-Zimmerman** [comment]
> > > Also facing this issue, even though i tried using the same organization number in webrtc.telnyx.com where it worked fine ![Screenshot 2022-08-19 at 9 35 25 PM](https://user-images.githubusercontent.com/18023153/185660554-3aeb17e8-effb-44b3-a660-171e9faa8a6a.png)
> > 
> > 
> > Please share the exact invite message sent on the socket
> > https://katb.in/porozosiwor [Edited with full logs]

Have you enabled the +91 call code area within your portal?




> > > I tried using the example app ![image](https://user-images.githubusercontent.com/18023153/185660230-30816c56-e8db-420b-9be1-f4c3907fec59.png)
> > 
> > 
> > Are you on the Main branch? This error isn't happening for me currently. I will spend some time this weekend looking into this though.
> > There is a refactor that we have planned which will simplify this flow and might indirectly fix this issue
> 
> Yes im using the main branch

Strange, I will look in
to this. You can't build a call without being logged in successfully which sets that sessionId. To me this sounds like somehow you aren't receiving a sessionId or logging in successfully before trying to create a call. Do you get a gateway registered log before attempting to make a call? 
![Screenshot 2022-08-19 at 17 21 00](https://user-images.githubusercontent.com/9112652/185663283-5d2680df-0106-43ed-bfa7-9870ac41f97b.png)

**Comment by icodelifee** [comment]
> > > > Also facing this issue, even though i tried using the same organization number in webrtc.telnyx.com where it worked fine ![Screenshot 2022-08-19 at 9 35 25 PM](https://user-images.githubusercontent.com/18023153/185660554-3aeb17e8-effb-44b3-a660-171e9faa8a6a.png)
> > > 
> > > 
> > > Please share the exact invite message sent on the socket
> > > [katb.in/porozosiwor](https://katb.in/porozosiwor) [Edited with full logs]
> 
> Have you enabled the +91 call code area within your portal?
> 
> > > > I tried using the example app ![image](https://user-images.githubusercontent.com/18023153/185660230-30816c56-e8db-420b-9be1-f4c3907fec59.png)
> > > 
> > > 
> > > Are you on the Main branch? This error isn't happening for me currently. I will spend some time this weekend looking into this though.
> > > There is a refactor that we have planned which will simplify this flow and might indirectly fix this issue
> > 
> > 
> > Yes im using the main branch
> 
> Strange, I will look in to this. You can't build a call without being logged in successfully which sets that sessionId. To me this sounds like somehow you aren't receiving a sessionId or logging in successfully before trying to create a call. Do you get a gateway registered log before attempting to make a call? ![Screenshot 2022-08-19 at 17 21 00](https://user-images.githubusercontent.com/9112652/185663283-5d2680df-0106-43ed-bfa7-9870ac41f97b.png)

Yes i do receive the gateway log and yes +91 is enabled, i was able to make calls in my app
![Screenshot 2022-08-19 at 9 53 12 PM](https://user-images.githubusercontent.com/18023153/185663692-09a8e1e5-df09-403b-9cd9-f68af30eac3f.png)

**Comment by icodelifee** [comment]
I'm in the Telnyx slack, if you would like you test with my credentials, maybe we could contact through there

**Comment by Oliver-Zimmerman** [comment]
Okay, I will look into this over the weekend and will do a relevant patch if required on Monday.

**Comment by icodelifee** [comment]
> > > Hi @icodelifee. Can You please test call via our test tool here:
> > > [webrtc.telnyx.com](https://webrtc.telnyx.com/)
> > > You can log in with sip credentials and call your flutter app. It would be nice to confirm if in this case there is still no audio on both ends so we can isolate it to the flutter SDK.
> > 
> > 
> > I tried the webrtc app and was able to make calls using credentials but for my use case, we only require outbound calls
> 
> So in this case please log into that web app and then call the web app credentials from your flutter application

i think we only have one telnyx number so i don't know if that will work or not

**Comment by icodelifee** [comment]
> Okay, I will look into this over the weekend and will do a relevant patch if required on Monday.

Thank you

**Comment by icodelifee** [comment]
Hey, any update?  @Oliver-Zimmerman

**Comment by Oliver-Zimmerman** [comment]
@icodelifee 
Fixed: 
https://github.com/team-telnyx/telnyx-webrtc-flutter/pull/14

Please test with telnyx_webrtc: ^0.0.4

**Comment by icodelifee** [comment]
> @icodelifee Fixed: #14
> 
> Please test with telnyx_webrtc: ^0.0.4

Thank you for the update, I'm testing it right now and the mic and audio still doesnt work and also SocketMethod.BYE and ANSWERED is not being returned in the callback

**Comment by icodelifee** [comment]
I had a chat with Telnyx representative the other day and i tried calling them through my app and i was able to hear and speak without any issue, i dont know why it doesnt work with other number

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee thanks for the PR! Ringing doesn't necessarily need to be added because you should receive an INVITE message that functions the same, however I will review your PR and test it and merge if all is working. 

In terms of BYE, what do you mean? You aren't getting a bye message when a call ends? It could be that the message isn't being interpreted by JSON as an actual BYE message. I can look into that

**Comment by icodelifee** [comment]
> Hi @icodelifee thanks for the PR! Ringing doesn't necessarily need to be added because you should receive an INVITE message that functions the same, however I will review your PR and test it and merge if all is working.
> 
> In terms of BYE, what do you mean? You aren't getting a bye message when a call ends? It could be that the message isn't being interpreted by JSON as an actual BYE message. I can look into that

Hi, I did not receive an INVITE message when I tried calling a number, I needed RINGING for a specific use case.

I only receive bye when endCall programmatically and not when I hang up the call on the receiving mobile. I want to know if the receiver hangup the call so I can update the UI .

**Comment by Oliver-Zimmerman** [comment]
@icodelifee can you confirm if this is calling a SIP Connection or an actual mobile number?

**Comment by icodelifee** [comment]
> @icodelifee can you confirm if this is calling a SIP Connection or an actual mobile number?

actual number

**Comment by Oliver-Zimmerman** [comment]
Thanks, I'll look into this right now

**Comment by Oliver-Zimmerman** [comment]
Okay I can reproduce, I was testing before with SIP connections. I will look into a solution

**Comment by icodelifee** [comment]
Hey @Oliver-Zimmerman, i just tried the example app and I'm not able to hear anything
![E63C8E87-57A2-4A70-AE99-B58F09ECAC1A_1_102_o](https://user-images.githubusercontent.com/18023153/186956200-3daa3522-1512-4fd4-b467-9088e2d06d1e.jpeg)
![telegram-cloud-photo-size-5-6073577828563136835-y](https://user-images.githubusercontent.com/18023153/186956244-9924f333-2660-44ce-a61f-c9a401d4f333.jpg)

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee, as mentioned before. I can reproduce this now and am working on it. Before I was testing sip connection to sip connection. The error is between sip connection and a real number. 

I will update you when I can.

**Comment by icodelifee** [comment]
Hi, any updates?
Thank you

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee, we are still working on this issue. It's very strange and may be related to the backend. We are entirely sure why it is only affecting PSTN calls. I am hoping to have a more substantial update for you by the end of today

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee, we have isolated the issue to something relating to the Flutter WebRTC library and how it is interacting with our backend. We are working to patch it at the moment. It involves Ice Candidates including a local host IP address. We are testing ignoring it as it comes in. Hoping to have it resolved today

**Comment by Oliver-Zimmerman** [comment]
@icodelifee we have a fix. I am opening a PR now. Once it is merged I will release a new version that contains your RINGING code as well

**Comment by Oliver-Zimmerman** [comment]
@icodelifee https://github.com/team-telnyx/telnyx-webrtc-flutter/pull/16

**Comment by Oliver-Zimmerman** [comment]
@icodelifee we have released 0.0.5
https://pub.dev/packages/telnyx_webrtc

Please test and close if it is working

**Comment by icodelifee** [comment]
Hey @Oliver-Zimmerman, I just tested and calls are working fine. Thank you.
But is there a way to switch from speakerphone to earpiece speaker.

**Comment by Oliver-Zimmerman** [comment]
Hi @icodelifee, it is possible but would require a small bit of development. If you open a feature request I can add it to the backlog and notify you when it is complete. 

Essentially we need to add a method that gets the current track and .enableSpearkerphone(true) or false. I will close this current issue for now. Please open a feature request instead.
